import { QAS_MOBILE_SERVER, QAS_WEB_SERVER, HOST_NAME } from "@env";

export const env = {
    NAME: "QAS",
    PROTOCOL: "https",
    HOST_NAME: HOST_NAME,
    PORT_WEB_SERVER: QAS_WEB_SERVER,
    PORT_MOBILE_SERVER: QAS_MOBILE_SERVER,
};
